"""Summary statistics and Markdown reporting."""

from __future__ import annotations

from datetime import UTC, datetime
from typing import TYPE_CHECKING, Any

import pandas as pd

from .classify import RELATIONSHIP_TYPES

if TYPE_CHECKING:
    from .analysis import AnalysisResult

PERSISTENCE_THRESHOLD = 0.95
"""Lag-1 autocorrelation above which a series is flagged as random-walk-like."""


def summary_statistics(result: AnalysisResult) -> dict[str, Any]:
    """Headline statistics for an analysis run."""
    t = result.table
    n = len(t)
    types = t["relationship_type"].value_counts()
    abs_corr = t["max_abs_correlation"]
    lagged = t[t["lag_detected"]]
    frame = result.data.frame
    persistent = [c for c in frame.columns if frame[c].autocorr(1) >= PERSISTENCE_THRESHOLD]
    return {
        "n_series": len(result.data.series),
        "n_observations": result.data.n_observations,
        "n_pairs": n,
        "n_skipped": len(result.skipped),
        "relationship_types": {k: int(types.get(k, 0)) for k in RELATIONSHIP_TYPES},
        "related_share": float((t["relationship_type"] != "none").mean()) if n else 0.0,
        "significant_share": float((t["significant_methods"] > 0).mean()) if n else 0.0,
        "mean_evidence_score": float(t["evidence_score"].mean()) if n else 0.0,
        "median_n_effective": float(t["n_effective"].median()) if n else 0.0,
        "strength": {
            "strong (>0.7)": int((abs_corr > 0.7).sum()),
            "moderate (0.3-0.7)": int(((abs_corr >= 0.3) & (abs_corr <= 0.7)).sum()),
            "weak (<0.3)": int((abs_corr < 0.3).sum()),
        },
        "strongest_method_counts": {
            k: int(v) for k, v in t["strongest_method"].value_counts().items()
        },
        "lag_detected": len(lagged),
        "mean_abs_detected_lag": float(lagged["ccf_peak_lag"].abs().mean())
        if len(lagged)
        else None,
        "high_persistence_series": persistent,
    }


def _md_table(df: pd.DataFrame, floatfmt: str = ".3f") -> str:
    def fmt(v: Any) -> str:
        if isinstance(v, float):
            return "" if pd.isna(v) else format(v, floatfmt)
        return str(v)

    header = "| " + " | ".join(map(str, df.columns)) + " |"
    sep = "|" + "|".join("---" for _ in df.columns) + "|"
    body = ["| " + " | ".join(fmt(v) for v in row) + " |" for row in df.itertuples(index=False)]
    return "\n".join([header, sep, *body])


def _persistence_note(series: list[str], detrend: str) -> list[str]:
    if not series or detrend == "difference":
        return []
    return [
        f"> **Note:** {len(series)} series have lag-1 autocorrelation >= {PERSISTENCE_THRESHOLD} "
        f"({', '.join(series)}). If they behave like random walks, re-run with "
        "`detrend='difference'`; autocorrelation-adjusted p-values are less reliable for "
        "non-stationary series.",
        "",
    ]


def render_markdown(
    result: AnalysisResult, top: int = 10, title: str = "TRACES Analysis Report"
) -> str:
    """Render a self-contained Markdown report of an analysis run."""
    from . import __version__

    s = summary_statistics(result)
    t = result.table
    source = result.data.source.name if result.data.source else "in-memory data"
    lines = [
        f"# {title}",
        "",
        f"_Generated by traces-ts {__version__} on {datetime.now(UTC):%Y-%m-%d} from `{source}`_",
        "",
        "## Overview",
        "",
        f"- Series: {s['n_series']} | Observations: {s['n_observations']} | Pairs analysed: {s['n_pairs']}",
        f"- Pairs with at least one significant correlation: {s['significant_share']:.1%}",
        f"- Pairs classified as related: {s['related_share']:.1%}",
        f"- Mean evidence score: {s['mean_evidence_score']:.3f}",
        f"- Median effective sample size: {s['median_n_effective']:.1f} (of {s['n_observations']})",
        f"- Significant lead/lag relationships detected: {s['lag_detected']}",
        "",
        *_persistence_note(s["high_persistence_series"], result.config.detrend),
        "## Configuration",
        "",
        _md_table(
            pd.DataFrame(
                list(result.config.to_dict().items()), columns=["parameter", "value"]
            ).astype(str)
        ),
        "",
        "## Relationship types",
        "",
        _md_table(pd.DataFrame(list(s["relationship_types"].items()), columns=["type", "pairs"])),
        "",
        "## Correlation strength (max of |r|, |rho|, |tau|)",
        "",
        _md_table(pd.DataFrame(list(s["strength"].items()), columns=["strength", "pairs"])),
        "",
        f"## Top {top} relationships by evidence score",
        "",
        _md_table(
            result.top(top)[
                [
                    "series_1",
                    "series_2",
                    "relationship_type",
                    "evidence_score",
                    "pearson",
                    "spearman",
                    "kendall",
                    "n_effective",
                    "ccf_peak_lag",
                ]
            ]
        ),
    ]

    for rel_type in RELATIONSHIP_TYPES:
        group = t[t["relationship_type"] == rel_type]
        if group.empty or rel_type == "none":
            continue
        lines += [
            "",
            f"### {rel_type.replace('_', '-').title()} relationships (n={len(group)})",
            "",
            _md_table(
                group.nlargest(5, "evidence_score")[
                    [
                        "series_1",
                        "series_2",
                        "evidence_score",
                        "max_abs_correlation",
                        "strongest_method",
                        "recommended_methods",
                        "ccf_peak_lag",
                    ]
                ]
            ),
        ]

    lines += [
        "",
        "---",
        "",
        "_Lag convention: a positive `ccf_peak_lag` means series_1 leads series_2. "
        "p-values are adjusted for autocorrelation and multiple testing as configured above._",
        "",
    ]
    return "\n".join(lines)
